### ISSUE TITLE
how to deal with more than two samples by DASE

### ISSUE THREAD

**Issue by xflicsu** [tenglab/DASE#1]
Hello DASE developers,
DASE provides a powerful differential analysis of SEs between groups.
I test this package and find it only provide sample parameter with "s1_r1_bam,s1_r2_bam, s2_r1_bam,s2_r2_bam".
I wonder how to deal with several samples more than two?
Thanks!

**Comment by tengmx** [comment]
We appreciate you are interested in our package and reporting this. We will address the issue and let you know soon.

**Comment by tengmx** [comment]
Hi, please try again with our package. More than two replicates are allowed now.
