### ISSUE TITLE
Memory map error

### ISSUE THREAD

**Issue by xflicsu** [tenglab/DASE#2]
Dear DASE developer,
When I test with your example, everything goes well.
But when I try to identify differential SE with DASE from several sample replicates, I caught the mermory map error.

My files
####
head -5 SE.bed
chr1    1120917 1139115 SE_1    .       .
chr1    1121163 1139152 SE_2    .       .
chr1    1121533 1139124 SE_3    .       .
chr1    1140570 1153175 SE_4    .       .
chr1    1141584 1152807 SE_5    .       .

head -5 peaks.bed
chr1    191246  191647  A_1   15.9002589872105        .
chr1    191281  191682  B_1    7.90608187809979        .
chr1    191282  191683  C_1    7.83505808362485        .
chr1    778345  778746  A_2   20.4147122713304        .
chr1    778349  778750  B_2    20.773066899224 .

head -5 H3K27ac.count
enhancer        S1        S2        S3        S4  ....
chr1_191246_191647      3       13      10      7 ...
chr1_778349_778750      24      17      45      28 ...
chr1_778983_779384      12      13      35      18 ...
chr1_779559_779960      12      11      20      20 ...

####
library(DASE)

se_path <- "SE.bed"
se_region <- read.table(se_path,sep="\t",header=F)
enhancer_path <- "peaks.bed"
enhancer_region <- read.table(enhancer_path,sep="\t",header=F)
count=read.table("H3K27ac.count",header=T,check.names=FALSE)
blacklist_path="hg38.blacklist.bed"
blacklist_region=read.table(blacklist_path,sep="\t",header=F)

DASE_ab <- DASE(se_in=se_region,e_in=enhancer_region,bl_file = blacklist_region,enhancer_count_table=count,c1_n=18,c2_n=23,permut=F,spline_fun = "smooth")

####

[1] "Step 1: merge and filter SE"
Step 2: calculate log2FC of constituent enhancer using Deseq2
   with raw enhancer count table.
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
-- replacing outliers and refitting for 37 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)
estimating dispersions
fitting model and testing
using 'apeglm' for LFC shrinkage. If used in published research, please cite:
    Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for
    sequence count data: removing the noise and preserving large differences.
    Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895

 *** caught segfault ***
address 0x7f4f7b073000, cause 'invalid permissions'
Traceback:
 1: forderv(x, by = xcols)
 2: bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,     ops, verbose = verbose)
 3: `[.data.table`(y, x, nomatch = if (all.x) NA else NULL, on = by,     allow.cartesian = allow.cartesian)
 4: y[x, nomatch = if (all.x) NA else NULL, on = by, allow.cartesian = allow.cartesian]
 5: merge.data.table(e_merge_by_chr, temp_output, by = "e_merge_name")
 6: merge(e_merge_by_chr, temp_output, by = "e_merge_name")
 7: enhancerFoldchange_count(e_df = e_in, se_df = merged_se_df, raw_count = enhancer_count_table,     c1_n = c1_n, c2_n = c2_n)
 8: DASE(se_in = se_region, e_in = enhancer_region, bl_file = blacklist_region,     enhancer_count_table = count, c1_n = 18, c2_n = 23, permut = F,     spline_fun = "smooth")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: *** longjmp causes uninitialized stack frame ***: /home/anaconda3/envs/DASE/lib/R/bin/exec/R terminated
======= Backtrace: =========
/lib64/libc.so.6(__fortify_fail+0x37)[0x7f5417430697]
/lib64/libc.so.6(+0x1185ad)[0x7f54174305ad]
/lib64/libc.so.6(__longjmp_chk+0x29)[0x7f5417430509]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x296278)[0x7f541797c278]
/lib64/libc.so.6(+0x36400)[0x7f541734e400]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/../../libgomp.so.1(+0x19705)[0x7f5417c4c705]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/../../libgomp.so.1(+0x19875)[0x7f5417c4c875]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/../../libgomp.so.1(+0x188bf)[0x7f5417c4b8bf]
/home/anaconda3/envs/DASE/lib/R/library/data.table/libs/data_table.so(radix_r+0x149a)[0x7f53f792a43a]
/home/anaconda3/envs/DASE/lib/R/library/data.table/libs/data_table.so(forder+0x18ad)[0x7f53f792bf8d]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1018ba)[0x7f54177e78ba]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x144077)[0x7f541782a077]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x14a424)[0x7f5417830424]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x14a424)[0x7f5417830424]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1a022b)[0x7f541788622b]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1a0663)[0x7f5417886663]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x13851e)[0x7f541781e51e]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x14874e)[0x7f541782e74e]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1a022b)[0x7f541788622b]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1a0663)[0x7f5417886663]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x1a0a27)[0x7f5417886a27]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x13c498)[0x7f5417822498]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x14a424)[0x7f5417830424]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x14a424)[0x7f5417830424]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x170)[0x7f541783e460]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15a06f)[0x7f541784006f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19f)[0x7f5417840e7f]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x29e)[0x7f541783e58e]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x15cb94)[0x7f5417842b94]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x5a9)[0x7f541783e899]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(Rf_ReplIteration+0x23d)[0x7f5417873e4d]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(+0x18e1f9)[0x7f54178741f9]
/home/anaconda3/envs/DASE/lib/R/bin/exec/../../lib/libR.so(run_Rmainloop+0x49)[0x7f54178742a9]
/home/anaconda3/envs/DASE/lib/R/bin/exec/R(main+0x1d)[0x55c729ba105d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f541733a555]
/home/anaconda3/envs/DASE/lib/R/bin/exec/R(+0x108d)[0x55c729ba108d]
======= Memory map: ========
55c729ba0000-55c729ba1000 r--p 00000000 fd:00 214765551214               /home/anaconda3/envs/DASE/lib/R/bin/exec/R
55c729ba1000-55c729ba2000 r-xp 00001000 fd:00 214765551214               /home/anaconda3/envs/DASE/lib/R/bin/exec/R
55c729ba2000-55c729ba3000 r--p 00002000 fd:00 214765551214               /home/anaconda3/envs/DASE/lib/R/bin/exec/R
55c729ba3000-55c729ba4000 r--p 00002000 fd:00 214765551214               /home/anaconda3/envs/DASE/lib/R/bin/exec/R
55c729ba4000-55c729ba5000 rw-p 00003000 fd:00 214765551214               /home/anaconda3/envs/DASE/lib/R/bin/exec/R
55c72b488000-55c797c77000 rw-p 00000000 00:00 0                          [heap]
7f4c54000000-7f4c54021000 rw-p 00000000 00:00 0
7f4c54021000-7f4c58000000 ---p 00000000 00:00 0
7f4c5c000000-7f4c5c022000 rw-p 00000000 00:00 0
7f4c5c022000-7f4c60000000 ---p 00000000 00:00 0
7f4c64000000-7f4c64022000 rw-p 00000000 00:00 0
7f4c64022000-7f4c68000000 ---p 00000000 00:00 0
7f4c6c000000-7f4c6c022000 rw-p 00000000 00:00 0
7f4c6c022000-7f4c70000000 ---p 00000000 00:00 0
7f4c74000000-7f4c74022000 rw-p 00000000 00:00 0
7f4c74022000-7f4c78000000 ---p 00000000 00:00 0
7f4c7c000000-7f4c7c022000 rw-p 00000000 00:00 0
7f4c7c022000-7f4c80000000 ---p 00000000 00:00 0
7f4c84000000-7f4c84022000 rw-p 00000000 00:00 0
7f4c84022000-7f4c88000000 ---p 00000000 00:00 0
7f4c8c000000-7f4c8c022000 rw-p 00000000 00:00 0
7f4c8c022000-7f4c90000000 ---p 00000000 00:00 0
7f4c94000000-7f4c94022000 rw-p 00000000 00:00 0
7f4c94022000-7f4c98000000 ---p 00000000 00:00 0
7f4c9c000000-7f4c9c022000 rw-p 00000000 00:00 0
7f4c9c022000-7f4ca0000000 ---p 00000000 00:00 0
7f4ca4000000-7f4ca4022000 rw-p 00000000 00:00 0
7f4ca4022000-7f4ca8000000 ---p 00000000 00:00 0
7f4cac000000-7f4cac022000 rw-p 00000000 00:00 0
7f4cac022000-7f4cb0000000 ---p 00000000 00:00 0
7f4cb4000000-7f4cb4022000 rw-p 00000000 00:00 0
7f4cb4022000-7f4cb8000000 ---p 00000000 00:00 0
7f4cbc000000-7f4cbc022000 rw-p 00000000 00:00 0
7f4cbc022000-7f4cc0000000 ---p 00000000 00:00 0
7f4cc4000000-7f4cc4022000 rw-p 00000000 00:00 0
7f4cc4022000-7f4cc8000000 ---p 00000000 00:00 0
7f4ccc000000-7f4ccc022000 rw-p 00000000 00:00 0
7f4ccc022000-7f4cd0000000 ---p 00000000 00:00 0
7f4cd4000000-7f4cd4022000 rw-p 00000000 00:00 0
7f4cd4022000-7f4cd8000000 ---p 00000000 00:00 0
7f4cdc000000-7f4cdc022000 rw-p 00000000 00:00 0
7f4cdc022000-7f4ce0000000 ---p 00000000 00:00 0
7f4ce4000000-7f4ce4022000 rw-p 00000000 00:00 0
7f4ce4022000-7f4ce8000000 ---p 00000000 00:00 0
7f4cec000000-7f4cec022000 rw-p 00000000 00:00 0
7f4cec022000-7f4cf0000000 ---p 00000000 00:00 0
7f4cf4000000-7f4cf4022000 rw-p 00000000 00:00 0
7f4cf4022000-7f4cf8000000 ---p 00000000 00:00 0
7f4cfc000000-7f4cfc022000 rw-p 00000000 00:00 0
7f4cfc022000-7f4d00000000 ---p 00000000 00:00 0
7f4d04000000-7f4d04022000 rw-p 00000000 00:00 0
7f4d04022000-7f4d08000000 ---p 00000000 00:00 0
7f4d0c000000-7f4d0c022000 rw-p 00000000 00:00 0
7f4d0c022000-7f4d10000000 ---p 00000000 00:00 0
7f4d14000000-7f4d14022000 rw-p 00000000 00:00 0
7f4d14022000-7f4d18000000 ---p 00000000 00:00 0
7f4d1c000000-7f4d1c022000 rw-p 00000000 00:00 0
7f4d1c022000-7f4d20000000 ---p 00000000 00:00 0
7f4d24000000-7f4d24022000 rw-p 00000000 00:00 0
7f4d24022000-7f4d28000000 ---p 00000000 00:00 0
7f4d2c000000-7f4d2c022000 rw-p 00000000 00:00 0
7f4d2c022000-7f4d30000000 ---p 00000000 00:00 0
7f4d34000000-7f4d34022000 rw-p 00000000 00:00 0
7f4d34022000-7f4d38000000 ---p 00000000 00:00 0
7f4d3c000000-7f4d3c022000 rw-p 00000000 00:00 0
7f4d3c022000-7f4d40000000 ---p 00000000 00:00 0
7f4d44000000-7f4d44022000 rw-p 00000000 00:00 0
7f4d44022000-7f4d48000000 ---p 00000000 00:00 0
7f4d4c000000-7f4d4c022000 rw-p 00000000 00:00 0
7f4d4c022000-7f4d50000000 ---p 00000000 00:00 0
7f4d54000000-7f4d54022000 rw-p 00000000 00:00 0
7f4d54022000-7f4d58000000 ---p 00000000 00:00 0
7f4d5c000000-7f4d5c022000 rw-p 00000000 00:00 0
7f4d5c022000-7f4d60000000 ---p 00000000 00:00 0
7f4d64000000-7f4d64022000 rw-p 00000000 00:00 0
7f4d64022000-7f4d68000000 ---p 00000000 00:00 0
7f4d6c000000-7f4d6c022000 rw-p 00000000 00:00 0
7f4d6c022000-7f4d70000000 ---p 00000000 00:00 0
7f4d74000000-7f4d74022000 rw-p 00000000 00:00 0
7f4d74022000-7f4d78000000 ---p 00000000 00:00 0
7f4d7c000000-7f4d7c022000 rw-p 00000000 00:00 0
7f4d7c022000-7f4d80000000 ---p 00000000 00:00 0
7f4d84000000-7f4d84022000 rw-p 00000000 00:00 0
7f4d84022000-7f4d88000000 ---p 00000000 00:00 0
7f4d8c000000-7f4d8c022000 rw-p 00000000 00:00 0
7f4d8c022000-7f4d90000000 ---p 00000000 00:00 0
7f4d94000000-7f4d94022000 rw-p 00000000 00:00 0
7f4d94022000-7f4d98000000 ---p 00000000 00:00 0
7f4d9c000000-7f4d9c022000 rw-p 00000000 00:00 0
7f4d9c022000-7f4da0000000 ---p 00000000 00:00 0
7f4da4000000-7f4da4022000 rw-p 00000000 00:00 0
7f4da4022000-7f4da8000000 ---p 00000000 00:00 0
7f4dac000000-7f4dac022000 rw-p 00000000 00:00 0
7f4dac022000-7f4db0000000 ---p 00000000 00:00 0
7f4db4000000-7f4db4022000 rw-p 00000000 00:00 0
7f4db4022000-7f4db8000000 ---p 00000000 00:00 0
7f4dbc000000-7f4dbc022000 rw-p 00000000 00:00 0
7f4dbc022000-7f4dc0000000 ---p 00000000 00:00 0
7f4dc4000000-7f4dc4022000 rw-p 00000000 00:00 0
7f4dc4022000-7f4dc8000000 ---p 00000000 00:00 0
7f4dcc000000-7f4dcc022000 rw-p 00000000 00:00 0
7f4dcc022000-7f4dd0000000 ---p 00000000 00:00 0
7f4dd4000000-7f4dd4022000 rw-p 00000000 00:00 0
7f4dd4022000-7f4dd8000000 ---p 00000000 00:00 0
7f4ddc000000-7f4ddc022000 rw-p 00000000 00:00 0
7f4ddc022000-7f4de0000000 ---p 00000000 00:00 0
7f4de4000000-7f4de4022000 rw-p 00000000 00:00 0 Aborted

**Comment by Xianglmoffitt** [comment]
Sorry for the late response. It seems the error is caused by the merge function, it may need lots of memory. Could you please tell me what is the dimension of each file (SE.bed, peaks.bed, and H3K27ac.count). I can test it to see if I have the same error.

**Comment by xflicsu** [comment]
> 

> dim(se_region)
[1] 7880    6
> dim(enhancer_region)
[1] 323703      6
> dim(count)
[1] 152299     62

Thanks for your help!

**Comment by Xianglmoffitt** [comment]
Hi @xflicsu, 

I have tested some dummy files with 6,535 SEs, 326,660 enhancers and 60 samples. Didn't run into a segmentation fault. I run it on a laptop with 16GB ram. 
There are some options you can try: 1) subsample the count table to see if it works; 2) set the R memory limits to Inf with "mem.maxVSize(vsize = Inf)";  3) reinstall DASE package or test it on other systems. Hope this will solve this issue.
